import sqlite3
import pandas as pd
import os
import re

def extract_queries(sql_content):
    """
    Extract queries from advanced_sql.sql separated by headers.
    Ignores queries marked with [SCHEMA EXAMPLE ONLY].
    """
    queries = []
    # Split by the numbering e.g., "-- 1.", "-- 2.", etc.
    blocks = re.split(r'-- \d+\.', sql_content)
    
    for i, block in enumerate(blocks[1:], 1): # Skip first block as it's header
        if "[SCHEMA EXAMPLE ONLY]" in block:
            continue
            
        # The first line of the block is the rest of the title from the split
        lines = block.strip().split('\n')[1:]
        query_lines = []
        for line in lines:
            if line.startswith('--') or line.startswith('---'):
                continue
            if line.strip():
                query_lines.append(line)
        
        query = "\n".join(query_lines).strip()
        if query:
            queries.append((i, query))
            
    return queries

def run_analysis():
    print("="*50)
    print("SQL ANALYSIS EXECUTION RUNNER")
    print("="*50)
    
    # Ensure targets are generated by initializing the live dashboard db briefly
    try:
        from live_dashboard import init_db
        conn = init_db()
    except Exception as e:
        print(f"Could not init DB from dashboard: {e}")
        # Fallback to direct connection if live_dashboard.py fails
        conn = sqlite3.connect('sales_data.db')
        
    output_dir = "sql_outputs"
    os.makedirs(output_dir, exist_ok=True)
    
    with open("advanced_sql.sql", "r") as f:
        sql_content = f.read()
        
    queries = extract_queries(sql_content)
    
    success_count = 0
    for q_num, query in queries:
        print(f"Executing Query {q_num}...")
        try:
            # We execute it using pandas so we can easily export to CSV
            df = pd.read_sql_query(query, conn)
            out_path = f"{output_dir}/query_{q_num}_result.csv"
            df.to_csv(out_path, index=False)
            print(f" [SUCCESS] Exported {len(df)} rows to {out_path}")
            success_count += 1
        except Exception as e:
            print(f" [FAILED] Error executing Query {q_num}:\n{e}")
            
    print("="*50)
    print(f"Analysis Complete: {success_count}/{len(queries)} queries executed successfully.")
    conn.close()

if __name__ == "__main__":
    run_analysis()
